const text = [
  "The sound of the waves crashing against the shore was both calming and invigorating. The salty breeze blew through her hair, and she felt the warmth of the sun on her skin. She closed her eyes and took a deep breath, feeling grateful to be alive in this moment.",
  `As she stepped onto the stage, the crowd erupted into cheers. She took a deep breath and began to sing, feeling the music flowing through her. It was a moment of pure exhilaration.`,
  `With the sun setting in the distance, she set up her camera and began to take photos. Each shot captured the beauty of the moment, the colors and textures blending together. It was a moment of artistic expression.`,
  `In the middle of the forest, she found a clearing. She sat down and closed her eyes, feeling the calmness of the surroundings. It was a moment of serenity and peacefulness.`,
  `The sound of the city was overwhelming, a constant buzz of noise. She put on her headphones and listened to her favorite music, feeling the chaos fade away. It was a moment of escape and relaxation.`,
  `On the top of the hill, she found a small cottage. She knocked on the door and was greeted by a friendly face. It was a moment of unexpected kindness.`,
  `As she stepped off the plane, she felt the heat of the sun and the smell of the ocean. She took a deep breath and felt the excitement of a new adventure. It was a moment of travel and exploration.`,
  "The neon lights of the cityscape danced before her eyes as she walked down the bustling street. People rushed past her, but she felt oddly disconnected from the chaos. She was lost in her thoughts, contemplating the purpose of life and the meaning of existence.",
  `The sweet aroma of freshly baked bread filled the air as she stepped into the quaint little bakery. She couldn't resist the temptation and bought a loaf of sourdough bread, still warm from the oven. She savored the first bite, relishing in the crunchy crust and soft, chewy center.`,
  `The rugged terrain of the mountain trail was challenging, but she was determined to reach the summit. She climbed higher and higher, her muscles burning with exertion. When she finally reached the top, the view took her breath away.`,
  `The sound of her child's laughter filled her heart with joy. She watched as he played, carefree and happy. She couldn't help but feel a sense of gratitude for the blessing of motherhood`,
  `The dark clouds loomed ominously in the sky, threatening to unleash a torrential downpour. She quickened her pace, hoping to make it home before the storm hit. As the first raindrops fell, she felt a sense of relief wash over her.`,
  `The smell of chlorine filled her nose as she dove into the cool water of the pool. She swam lap after lap, feeling the water's embrace. It was a moment of pure bliss.`,
  `The scent of freshly cut grass filled her nostrils as she walked barefoot through the lush green lawn. The sun was shining, and she felt content in the simple pleasure of being alive.`,
  `The sound of the orchestra filled the auditorium, each note a symphony of emotion. She closed her eyes and let the music wash over her, feeling the vibrations in her soul.`,
  `In the middle of the museum, she found a painting that spoke to her. She stood in front of it, feeling a sense of emotion and understanding. It was a moment of artistic interpretation.`,
  `As she walked through the bustling market, she saw a vendor selling fresh fruits and vegetables. She bought some and took a bite, feeling the sweetness and juiciness. It was a moment of culinary discovery.`,
  `The scent of lavender filled the air as she stepped into the quaint little shop. She perused the shelves, admiring the various herbs and teas. She couldn't resist buying a bundle of dried lavender, the delicate fragrance calming her senses.`,
  `The chill of the autumn breeze nipped at her cheeks as she walked through the park. She watched as the leaves danced in the wind, their vibrant colors a testament to the beauty of change.`,
  `The sound of her pen scratching against the paper was soothing, a cathartic release of her thoughts and feelings. Writing had always been her escape, a way to make sense of the world.`,
  `The smell of coffee filled her nostrils as she stepped into the cozy cafe. She ordered her usual latte and found a quiet corner to read. The warmth of the drink and the comfort of the book made her feel at home.`,
  `The crisp air of winter bit at her skin as she skated across the frozen pond. The blades glided effortlessly, leaving a trail of marks in the ice. She felt alive and free.`,
  `The scent of pine needles filled her nose as she decorated the Christmas tree. She hung ornaments with care, each one a memory from years past. The twinkling lights and the joy of the season filled her heart.`,
  `The sound of her heels clicking against the pavement echoed through the empty streets. She walked alone, lost in thought, pondering the mysteries of life.`,
  `The sun was setting in a blaze of oranges and pinks, casting a warm glow over the horizon. She sat on the porch, sipping her tea and watching as the world slowly turned to darkness. It was a moment of peaceful reflection.`,
  `The sound of rain tapping against the roof was soothing, a gentle lullaby to her restless mind. She curled up with a book, content to spend the day indoors, lost in a fictional world.`,
  `The scent of vanilla and cinnamon filled the air as she baked a batch of cupcakes. She hummed to herself, enjoying the simple pleasure of creating something delicious. As she frosted the cupcakes, she felt a sense of accomplishment and pride.`,
  `As she stepped into the art gallery, she was immediately drawn to a sculpture in the center of the room. She walked around it, feeling the curves and textures. It was a moment of artistic appreciation.`,
  `The wind howled through the trees, a wild and untamed force. She stood on the hill, arms outstretched, letting the wind whip through her hair. It was a moment of raw, exhilarating freedom.`,
  `With the snow falling softly outside, she sat by the fireplace with a warm blanket. She sipped on a hot drink and read her favorite book, feeling the coziness of the moment. It was a moment of winter comfort.`,
  `With the wind blowing fiercely, she took a deep breath and stepped onto the zip line. She soared through the air, feeling the adrenaline rush through her. It was a moment of adventure and thrill.`,
  `As she sat in the cafe, she saw a couple across the room sharing a kiss. She felt a sense of romance in the air. It was a moment of love and connection.`,
  `The sound of her baby's coos filled the air, a sweet melody to her ears. She held the tiny bundle close, feeling the weight of the responsibility of motherhood. But in that moment, all she felt was love.`,
  `The scent of freshly mowed grass filled her nose as she lounged in the backyard. She closed her eyes and soaked in the warmth of the sun, feeling a sense of contentment and peace.`,
  `The taste of the salty ocean air was refreshing, a cool breeze on her lips. She walked along the beach, feeling the sand between her toes and the water lapping at her feet. It was a moment of pure relaxation.`,
  `The sound of the guitar filled the room, the notes weaving together in a tapestry of sound. She watched as the musician played, his fingers moving deftly over the strings. It was a moment of awe-inspiring talent.`,
  `The smell of freshly brewed coffee filled her nostrils as she stepped into the cozy cafe. She ordered a cappuccino and found a comfortable seat by the window. As she sipped the warm drink, she felt a sense of belonging in the bustling atmosphere.`,
  `The feel of the cool water was refreshing, a balm to her hot skin. She swam laps in the pool, feeling her muscles stretch and strengthen. It was a moment of rejuvenation.`,
  `The sound of her voice echoed through the empty room, the words tumbling out in a stream of consciousness. She spoke her truth, unafraid and unapologetic. It was a moment of bravery and vulnerability.`,
  `The scent of freshly baked bread filled her kitchen, a comforting aroma. She kneaded the dough, feeling the texture and weight in her hands. As she pulled the finished loaf from the oven, she felt a sense of satisfaction.`,
  `The sight of the snow-covered landscape was breathtaking, a winter wonderland. She donned her snow gear and headed outside, feeling the crunch of the snow under her boots. It was a moment of childlike wonder and excitement.`,
  `The sound of the wind chimes filled the air, a melodic tune. She sat on the porch swing, sipping her tea and enjoying the gentle breeze. It was a moment of relaxation and serenity.`,
  `The scent of the ocean was salty and fresh, a reminder of the vastness of the world. She sat on the cliff, watching as the waves crashed against the rocks below. It was a moment of peaceful contemplation.`,
  `In the middle of the concert, she felt a tap on her shoulder. She turned around to see an old friend. It was a moment of unexpected reunion.`,
  `The feel of the sand between her toes was soothing, a connection to the earth. She walked along the beach, feeling the salty breeze on her face. It was a moment of tranquility and relaxation.`,
  `The scent of freshly baked cookies filled her home, a warm and inviting aroma. She took a bite, feeling the sweetness and crunch of each cookie. It was a moment of indulgence and comfort.`,
  `The feel of the soft blanket was comforting, a hug in fabric form. She curled up with a book, feeling the weight of the world lift off her shoulders. It was a moment of self-care and relaxation.`,
  `The sound of the rain was soothing, a gentle pattering on the roof. She sat by the window, watching as the drops streaked down the glass. It was a moment of peacefulness and contentment.`,
  `The sight of the majestic mountains was awe-inspiring, a symbol of strength and power. She hiked to the peak, feeling the accomplishment and exhilaration. It was a moment of adventure and triumph.`,
  `The sound of the waterfall was mesmerizing, a rush of water and sound. She stood at the edge, feeling the mist on her face. It was a moment of natural beauty and wonder.`,
];

export default text;
